### ISSUE TITLE
[Bug]: If model has close to 1,000,000 rows getFormSelectOptions data.model_id fails

### ISSUE THREAD

**Issue by krognome** [Tschucki/filament-workflows#1]
### What happened?

Is there a way for me to limit the number of ID pulled or disable and maybe only keep search enabled on large database tables for model IDs? Maybe a config that can be published that we may set an option like this and maybe models that are massive in size. I am thinking I may have to set this package as a custom vendor package in my Laravel project so it no longer pulls updates and references my local custom package so I may go in and fix these things or maybe I should pull this repo and connect the composer package to that copy of the GitHub repo so I may fix this myself? I may end up having to do this. Thanks for this package though guys it's pretty genius and exactly what I needed. If done right and it looks like it has been for the most part everyone should want this package really it gives me the power to enable my client with the ability to create their own system or triggers and the possibilities are endless!

### How to reproduce the bug

Tie this package to a model with almost 1 million rows then try to get the model ID on step 1 or simply just select that model because it seems like the system automatically starts pulling the IDs for the model as soon as you select it.

### Package Version

0.0.1

### PHP Version

8.2

### Laravel Version

10

**Comment by Tschucki** [comment]
I will look into this!

**Comment by krognome** [comment]
I apologize this error maybe related to my server's configuration:
[Fri Feb 23 13:58:34.849029 2024] [php:error] [pid 29260] [client 192.168.96.1:49731] PHP Fatal error:  Allowed memory size of 1342177280 bytes exhausted (tried to allocate 12288 bytes) in /var/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php on line 601, referer: http://spotlightdeveloper.com/admin/filament-workflows/create
[Fri Feb 23 13:58:34.887180 2024] [php:error] [pid 29260] [client 192.168.96.1:49731] PHP Fatal error:  Allowed memory size of 1342177280 bytes exhausted (tried to allocate 57344 bytes) in /var/www/vendor/spatie/ignition/src/ErrorPage/ErrorPageViewModel.php on line 104, referer: http://spotlightdeveloper.com/admin/filament-workflows/create
[Fri Feb 23 14:00:15.262487 2024] [php:error] [pid 20707] [client 192.168.96.1:49815] PHP Fatal error:  Allowed memory size of 1342177280 bytes exhausted (tried to allocate 4096 bytes) in /var/www/vendor/laravel/framework/src/Illuminate/Collections/Arr.php on line 935, referer: http://spotlightdeveloper.com/admin/filament-workflows/create
[Fri Feb 23 14:00:15.879634 2024] [core:notice] [pid 23195] AH00052: child pid 20707 exit signal Segmentation fault (11)
[Fri Feb 23 14:17:35.297868 2024] [php:error] [pid 1640] [client 192.168.96.1:50647] PHP Fatal error:  Allowed memory size of 1342177280 bytes exhausted (tried to allocate 12288 bytes) in /var/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php on line 601, referer: http://spotlightdeveloper.com/admin/filament-workflows/create
[Fri Feb 23 14:17:35.390106 2024] [php:error] [pid 1640] [client 192.168.96.1:50647] PHP Fatal error:  Allowed memory size of 1342177280 bytes exhausted (tried to allocate 57344 bytes) in /var/www/vendor/spatie/ignition/src/ErrorPage/ErrorPageViewModel.php on line 104, referer: http://spotlightdeveloper.com/admin/filament-workflows/create

**Comment by krognome** [comment]
I just checked my memory limit is pretty high: 1280MB

**Comment by krognome** [comment]
I added a fix that works and allows search for the modal ID select field. I updated: 

Resources/FilamentWorkflowResource.php line #29 to: 

`Forms\Components\Select::make('model_id')->searchable()->nullable()->getSearchResultsUsing(fn (string $search, Forms\Get $get) => $get('model_type') ? self::getModelOptions(app($get('model_type')), $search) : [])->getOptionLabelUsing(fn ($value, Forms\Get $get): ?string => app($get('model_type'))::find($value)?->id),`

Concerns/CanSetupWorkflows.php line #99 to: 
```
public static function getModelOptions(?Model $model, $search="")
    {
        if (! $model) {
            return [];
        }

        if (self::modelUsesTrait($model, InteractsWithWorkflow::class)) {
            if(!empty($search)){
                return $model::where('id', 'like', '%'.$search.'%')->take(1000)->get()->mapWithKeys(function ($model, $key) {
                    return [
                        $model->getKey() => $model->getTitelAttributeForWorkflow(),
                    ];
                });
            }else{
                return $model::all()->take(1000)->mapWithKeys(function ($model, $key) {
                    return [
                        $model->getKey() => $model->getTitelAttributeForWorkflow(),
                    ];
                });
            }
        }

        throw new \InvalidArgumentException(sprintf('Model %s does not use trait %s', $model::class, InteractsWithWorkflow::class));
    }
```

This is working well but it only get 1,000 rows by default then when you run a search it will pull only 1,000 rows on the search but this should work well for everyone really because they can simply search for the ID they want if they plan on using that select.

**Comment by krognome** [comment]
What do you guys think about adding this method to your Action example? Many will not know how to set the name and it will be blank by default which will look like a bug because an option lable/title will not show on the action page it will just be blank without it:

public function getActionName(): string
    {
        return 'Confirm Service';
    }

**Comment by krognome** [comment]
Or you could show them the complete BaseAction class they are extending:

```
<?php

namespace Tschucki\FilamentWorkflows\WorkflowActions;

use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Queue\SerializesModels;

class BaseAction implements ShouldQueue
{
    use Dispatchable;
    use InteractsWithQueue;
    use Queueable;
    use SerializesModels;

    public function handle(): void
    {
        //
    }

    public function getActionName(): string
    {
        return '';
    }

    public function getActionDescription(): string
    {
        return '';
    }

    public function getActionCategory(): string
    {
        return '';
    }

    public function getActionIcon(): string
    {
        return 'heroicon-o-forward';
    }
}
```

**Comment by Tschucki** [comment]
Thanks for reporting this issue. 
I have added a config to influence this behaviour and published a new [release](https://github.com/Tschucki/filament-workflows/releases/tag/0.0.2).

**Comment by krognome** [comment]
Thank you Tschucki. I ended up making the repo a custom repo in my project so I can fully customize it. I am going to add parameters for all of my actions such as action: Charge client X and send report to X email address of all failed and success etc, etc. If I was to go all out with this I would find a way to scan all controllers attached to specific models and auto create actions from them and take parameters from the controllers methods or actions and auto generate dynamic inputs allowing the user to enter or select options/parameters. With that this package would be a gold. Many developers would not want to give their clients access to this because they would feel like they are risking losing that custom work if the user/client can create it all themselves but I strongly believe if you give your client the keys to the kingdom and maintain a good relationship they will want more and reward you for helping them dominate their market etc. :) Thanks for being awesome and adding that.
