### ISSUE TITLE
No options in Action List

### ISSUE THREAD

**Issue by threecolors-lab** [Tschucki/filament-workflows#5]
### What happened?

I get no options in Action

![image](https://github.com/Tschucki/filament-workflows/assets/149889332/2be9f085-a84f-4f2c-80c9-a62d5f82097e)

How to solve that problem?

### How to reproduce the bug

Create Basic : ok
Create Trigger: ok

### Package Version

0.0.2

### PHP Version

8.1

### Laravel Version

10

### Which operating systems does with happen with?

Windows

**Comment by Tschucki** [comment]
You need to make sure your Action extends the BaseAction.
You can place the Action where ever you want. The Plugin will find any class that extends the BaseAction.

See:
https://github.com/Tschucki/filament-workflows?tab=readme-ov-file#create-an-action

Example Action:
```php
<?php

namespace App\Actions;

use Tschucki\FilamentWorkflows\WorkflowActions\BaseAction;

class TestAction extends BaseAction
{
    public function __construct()
    {
        //
    }
    
    public function handle(): void
    {
        //
    }

    public function getActionName(): string
    {
        return 'Name';
    }
}

```
