### ISSUE TITLE
[Bug]: Not installable with Laravel 11

### ISSUE THREAD

**Issue by WojciechRhdt** [Tschucki/filament-workflows#8]
### What happened?

When I try to install this package by composer I get the following error:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires tschucki/filament-workflows * -> satisfiable by tschucki/filament-workflows[0.0.1, 0.0.2].
    - tschucki/filament-workflows[0.0.1, ..., 0.0.2] require illuminate/contracts ^10.0 -> found illuminate/contracts[v10.0.0, ..., v10.48.10] but these were not loaded, likely because it conflicts with another require.

### How to reproduce the bug

composer require tschucki/filament-workflows

### Package Version

0.0.2

### PHP Version

8.2

### Laravel Version

11

**Comment by Tschucki** [comment]
I will fix this asap

**Comment by WojciechRhdt** [comment]
Danke ;)

**Comment by Tschucki** [comment]
I've published a new release.

You can now use the plugin with Laravel 11. <3
